[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
MainTitleString = "Example Historical Traces and Current Streamflow"

[SubProduct 1]

GraphType = "Line"

[Data 1.1]

TSID = "08251500.USGS.Streamflow.Day[1950]~HydroBase"
TSAlias = "08251500_1950"

[Data 1.2]

TSID = "08251500.USGS.Streamflow.Day[1970]~HydroBase"
TSAlias = "08251500_1970"

[Data 1.3]

TSID = "08251500.USGS.Streamflow.Day[1980]~HydroBase"
TSAlias = "08251500_1980"

[Data 1.4]

TSID = "08251500.DWR.Streamflow-DISCHRG.Day~HydroBase"
TSAlias = "lobatos_current"
