[Product]

ProductType = "Graph"
TotalHeight = "400"
TotalWidth = "600"

[SubProduct 1]

GraphType = "Line"
MainTitleString = "ALFRED SLOSS DITCH NO 1"
SubTitleString = "Daily Diversions"
LayoutYPercent = ""

[Data 1.1]

Color = "Blue"
TSID = "3800502.DWR.DivTotal.Day~ColoradoWaterHBGuest"

[SubProduct 2]

GraphType = "Line"
MainTitleString = "ALFRED SLOSS DITCH NO 1"
SubTitleString = "Monthly and Annual Diversions"

[Data 2.1]

Color = "Blue"
TSID = "3800502.DWR.DivTotal.Month~ColoradoWaterHBGuest"

[Data 2.2]

Color = "Blue"
LineWidth = "3"
TSAlias = "3800502-CalYear"
TSID = "3800502.DWR.DivTotal.Year~ColoradoWaterHBGuest"
