[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
MainTitleString = "Simple Example of Reading StateMod Binary File"

[SubProduct 1]

GraphType = "Line"
LayoutYPercent = ""

[Data 1.1]

TSID = "Dem_2.StateMod.River_Outflow.Month~StateModB~ex119C2.b43"
SymbolSize = "6"
SymbolStyle = "Circle-Filled"

[Data 1.2]

TSID = "Dem_2.StateMod.Available_Flow.Month~StateModB~ex119C2.b43"
SymbolSize = "0"
SymbolStyle = "None"

[Data 1.3]

TSID = "Dem_3.StateMod.River_Outflow.Month~StateModB~ex119C2.b43"
SymbolSize = "6"
SymbolStyle = "Circle-Filled"

[Data 1.4]

TSID = "Dem_3.StateMod.Available_Flow.Month~StateModB~ex119C2.b43"
SymbolSize = "0"
SymbolStyle = "None"
