[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
MainTitleString = "White Model Total Net Absolute Decrees"

[SubProduct 1]

GraphType = "Line"
LeftYAxisMax = "2378.1500000000005"
LeftYAxisLabelPrecision = "0"
LayoutYPercent = ""
PeriodStart = "1850"
PeriodEnd = "2010"

[Data 1.1]

TSID = "DataSet.StateMod.DiversionWaterRightsTotal.Year"
TSAlias = "DataSet-Decree"
Color = "Blue"
LineWidth = "2"
