#HeaderRevision 0
#
# File generated by...
# program:      TSTool 9.05.01 beta (2009-10-19)
# user:         sam
# date:         Wed Oct 28 16:57:58 MDT 2009
# host:         AMAZON
# directory:    C:\Develop\TSTool_SourceBuild\TSTool\test\regression\UserManualExamples\TestCases\CommandReference\AnalyzePattern
# command line: TSTool -home test/operational/RTi
#------------------------------------------------
#
# StateMod format pattern time series
# ***********************************
#
# Years Shown = Calendar Years
# The period of record for each time series may vary
# because of the original input and data processing steps.
#
#     TS ID                    Type   Source   Units  Period of Record    Location    Description
#   1 06720500.DWR.Pattern.mon Patter DWR             May/1926 - Sep/2008 06720500    SOUTH PLATTE RIVER AT HE
#   2 06754000.DWR.Pattern.mon Patter DWR             May/1901 - Sep/2008 06754000    SOUTH PLATTE RIVER NEAR 
#
#>EndHeader
#>
#> Yr ID            Jan     Feb     Mar     Apr     May     Jun     Jul     Aug     Sep     Oct     Nov     Dec     
#>-e-b----------eb------eb------eb------eb------eb------eb------eb------eb------eb------eb------eb------eb------e
    1/1901  -     12/2008       CYR
1901 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1901 06754000      -999.0  -999.0  -999.0  -999.0     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG
1902 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1902 06754000         AVG     AVG     AVG     DRY     DRY     DRY     DRY     DRY     AVG     DRY     DRY     AVG
1903 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1903 06754000         AVG     AVG     WET     AVG     DRY     AVG     AVG     DRY     DRY     DRY     DRY     DRY
1904 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1904 06754000      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1905 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1905 06754000      -999.0  -999.0     DRY     WET     WET     WET     DRY     DRY     DRY     DRY     AVG     DRY
1906 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1906 06754000         DRY     DRY     AVG     AVG     AVG     DRY     AVG     DRY     AVG     WET     WET     WET
1907 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1907 06754000         WET     AVG     AVG     AVG     AVG     AVG     WET     WET     AVG     AVG     AVG     AVG
1908 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1908 06754000         AVG     DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY     AVG     DRY     DRY
1909 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1909 06754000         DRY     AVG     WET     WET     AVG     WET     WET     AVG     WET     WET     WET     WET
1910 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1910 06754000         WET     WET     WET     AVG     DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY
1911 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1911 06754000         DRY     DRY     DRY     DRY     DRY     DRY     AVG     DRY     DRY     DRY     DRY     DRY
1912 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1912 06754000         DRY     DRY     DRY     AVG     AVG     AVG     WET     WET     AVG     AVG     AVG     WET
1913 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1913 06754000      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1914 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1914 06754000         WET     WET     WET     WET     WET     WET     AVG     WET     AVG     WET     AVG     AVG
1915 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1915 06754000         AVG     AVG     AVG     WET     WET     WET     AVG     AVG     AVG     WET     WET     AVG
1916 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1916 06754000         AVG     WET     AVG     AVG     AVG     DRY     DRY     AVG     DRY     WET     AVG     AVG
1917 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1917 06754000         AVG     AVG     AVG     AVG     WET     WET     WET     AVG     AVG     AVG     AVG     AVG
1918 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1918 06754000         AVG     AVG     AVG     AVG     AVG     AVG     WET     AVG     AVG     WET     AVG     WET
1919 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1919 06754000         WET     AVG     AVG     AVG     AVG     DRY     DRY     AVG     AVG     AVG     AVG     AVG
1920 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1920 06754000         AVG     AVG     DRY     AVG     WET     AVG     AVG     AVG     AVG     AVG     AVG     AVG
1921 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1921 06754000         AVG     AVG     DRY     WET     AVG     WET     AVG     WET     AVG     AVG     AVG     WET
1922 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1922 06754000         AVG     AVG     AVG     AVG     DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY
1923 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1923 06754000         DRY     AVG     AVG     AVG     AVG     WET     WET     WET     AVG     WET     WET     WET
1924 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1924 06754000         WET     WET     WET     WET     WET     WET     AVG     DRY     AVG     AVG     AVG     AVG
1925 06720500      -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0  -999.0
1925 06754000         AVG     AVG     DRY     DRY     DRY     DRY     DRY     AVG     DRY     AVG     AVG     AVG
1926 06720500      -999.0  -999.0  -999.0  -999.0     WET     WET     WET     AVG     DRY     AVG     AVG     AVG
1926 06754000         AVG     AVG     DRY     WET     WET     WET     WET     AVG     AVG     AVG     AVG     AVG
1927 06720500         DRY     DRY     DRY     AVG     DRY     DRY     AVG     AVG     AVG     AVG     DRY     AVG
1927 06754000         AVG     DRY     AVG     AVG     AVG     AVG     AVG     WET     AVG     AVG     AVG     AVG
1928 06720500         AVG     AVG     DRY     DRY     AVG     AVG     DRY     DRY     DRY     AVG     DRY     DRY
1928 06754000         AVG     AVG     AVG     AVG     WET     AVG     WET     AVG     AVG     AVG     AVG     AVG
1929 06720500         DRY     DRY     AVG     AVG     DRY     DRY     DRY     WET     AVG     AVG     AVG     AVG
1929 06754000         AVG     DRY     AVG     AVG     AVG     DRY     DRY     AVG     WET     AVG     AVG     AVG
1930 06720500         AVG     AVG     DRY     AVG     DRY     AVG     AVG     WET     AVG     AVG     AVG     DRY
1930 06754000         AVG     WET     AVG     AVG     DRY     DRY     DRY     WET     AVG     AVG     AVG     AVG
1931 06720500         DRY     DRY     DRY     DRY     AVG     AVG     DRY     DRY     DRY     DRY     AVG     AVG
1931 06754000         DRY     DRY     AVG     AVG     AVG     DRY     DRY     DRY     DRY     DRY     DRY     AVG
1932 06720500         AVG     AVG     AVG     DRY     DRY     DRY     AVG     DRY     DRY     DRY     DRY     DRY
1932 06754000         DRY     AVG     DRY     DRY     DRY     DRY     AVG     DRY     DRY     DRY     DRY     DRY
1933 06720500         DRY     AVG     DRY     AVG     WET     AVG     AVG     DRY     WET     DRY     DRY     AVG
1933 06754000         DRY     DRY     DRY     DRY     WET     AVG     AVG     AVG     WET     DRY     AVG     AVG
1934 06720500         AVG     AVG     DRY     DRY     AVG     DRY     DRY     DRY     DRY     DRY     DRY     DRY
1934 06754000         AVG     AVG     DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY
1935 06720500         DRY     DRY     DRY     DRY     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG
1935 06754000         DRY     DRY     DRY     DRY     AVG     AVG     DRY     DRY     AVG     AVG     AVG     DRY
1936 06720500         AVG     DRY     AVG     DRY     AVG     AVG     AVG     WET     WET     AVG     AVG     AVG
1936 06754000         DRY     DRY     DRY     DRY     DRY     AVG     DRY     AVG     AVG     AVG     AVG     AVG
1937 06720500         AVG     AVG     AVG     AVG     AVG     AVG     AVG     DRY     AVG     DRY     AVG     DRY
1937 06754000         DRY     AVG     AVG     AVG     DRY     AVG     AVG     DRY     DRY     DRY     DRY     DRY
1938 06720500         DRY     AVG     DRY     AVG     WET     AVG     AVG     AVG     WET     AVG     WET     WET
1938 06754000         DRY     AVG     DRY     AVG     AVG     AVG     AVG     AVG     WET     AVG     WET     WET
1939 06720500         AVG     AVG     WET     WET     AVG     AVG     DRY     DRY     DRY     DRY     DRY     AVG
1939 06754000         WET     AVG     WET     WET     AVG     DRY     DRY     DRY     DRY     DRY     DRY     DRY
1940 06720500         DRY     AVG     AVG     AVG     DRY     DRY     DRY     DRY     AVG     DRY     AVG     DRY
1940 06754000         DRY     AVG     AVG     DRY     DRY     DRY     DRY     DRY     AVG     DRY     DRY     DRY
1941 06720500         AVG     AVG     DRY     DRY     AVG     WET     AVG     AVG     AVG     AVG     AVG     AVG
1941 06754000         DRY     DRY     DRY     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG
1942 06720500         AVG     AVG     WET     WET     WET     WET     WET     AVG     AVG     AVG     AVG     WET
1942 06754000         AVG     DRY     WET     WET     WET     WET     AVG     AVG     AVG     AVG     AVG     WET
1943 06720500         AVG     DRY     AVG     AVG     AVG     AVG     AVG     AVG     DRY     DRY     DRY     DRY
1943 06754000         AVG     AVG     AVG     AVG     AVG     AVG     AVG     DRY     DRY     DRY     DRY     DRY
1944 06720500         AVG     DRY     AVG     AVG     WET     AVG     AVG     DRY     DRY     DRY     DRY     DRY
1944 06754000         DRY     DRY     AVG     AVG     WET     AVG     AVG     DRY     DRY     DRY     DRY     DRY
1945 06720500         DRY     DRY     AVG     DRY     DRY     DRY     AVG     WET     AVG     AVG     AVG     AVG
1945 06754000         AVG     DRY     DRY     AVG     AVG     AVG     AVG     WET     AVG     AVG     AVG     AVG
1946 06720500         AVG     DRY     AVG     AVG     DRY     DRY     DRY     DRY     AVG     DRY     AVG     AVG
1946 06754000         AVG     DRY     AVG     DRY     DRY     DRY     AVG     DRY     AVG     DRY     AVG     AVG
1947 06720500         AVG     AVG     AVG     AVG     WET     WET     WET     WET     WET     AVG     WET     AVG
1947 06754000         AVG     DRY     WET     AVG     AVG     WET     WET     AVG     AVG     WET     WET     AVG
1948 06720500         AVG     WET     WET     WET     WET     WET     AVG     AVG     DRY     DRY     DRY     DRY
1948 06754000         AVG     WET     WET     WET     AVG     AVG     DRY     DRY     DRY     DRY     DRY     DRY
1949 06720500         DRY     DRY     AVG     DRY     AVG     WET     WET     AVG     AVG     AVG     AVG     AVG
1949 06754000         AVG     AVG     AVG     AVG     AVG     WET     WET     DRY     AVG     AVG     AVG     DRY
1950 06720500         DRY     AVG     DRY     DRY     DRY     AVG     DRY     DRY     DRY     DRY     DRY     DRY
1950 06754000         DRY     DRY     DRY     DRY     DRY     AVG     DRY     DRY     DRY     DRY     DRY     DRY
1951 06720500         AVG     AVG     DRY     DRY     DRY     AVG     AVG     AVG     DRY     AVG     AVG     DRY
1951 06754000         DRY     AVG     DRY     DRY     AVG     AVG     AVG     WET     AVG     AVG     AVG     AVG
1952 06720500         DRY     DRY     DRY     DRY     AVG     AVG     AVG     AVG     DRY     DRY     DRY     DRY
1952 06754000         AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     DRY     DRY     DRY     AVG
1953 06720500         DRY     DRY     DRY     DRY     AVG     AVG     AVG     AVG     DRY     AVG     DRY     AVG
1953 06754000         AVG     DRY     DRY     AVG     DRY     DRY     AVG     AVG     DRY     DRY     AVG     DRY
1954 06720500         AVG     DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY
1954 06754000         DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY
1955 06720500         DRY     DRY     DRY     DRY     AVG     DRY     DRY     AVG     AVG     DRY     DRY     DRY
1955 06754000         DRY     DRY     DRY     DRY     DRY     DRY     DRY     AVG     DRY     DRY     DRY     DRY
1956 06720500         DRY     DRY     DRY     DRY     AVG     AVG     DRY     DRY     DRY     DRY     DRY     DRY
1956 06754000         DRY     DRY     DRY     DRY     AVG     DRY     DRY     AVG     DRY     DRY     DRY     DRY
1957 06720500         DRY     AVG     AVG     DRY     WET     WET     WET     WET     AVG     AVG     AVG     AVG
1957 06754000         DRY     DRY     DRY     AVG     WET     WET     WET     WET     AVG     AVG     WET     WET
1958 06720500         AVG     DRY     AVG     AVG     WET     AVG     DRY     DRY     DRY     DRY     DRY     DRY
1958 06754000         AVG     AVG     AVG     WET     WET     AVG     AVG     AVG     DRY     AVG     DRY     DRY
1959 06720500         DRY     DRY     DRY     AVG     AVG     AVG     DRY     DRY     DRY     AVG     DRY     DRY
1959 06754000         DRY     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG
1960 06720500         DRY     AVG     WET     WET     AVG     AVG     AVG     DRY     DRY     AVG     DRY     DRY
1960 06754000         AVG     AVG     WET     AVG     AVG     AVG     AVG     AVG     DRY     AVG     DRY     AVG
1961 06720500         DRY     DRY     AVG     AVG     AVG     AVG     AVG     AVG     WET     WET     WET     WET
1961 06754000         AVG     DRY     AVG     AVG     AVG     WET     AVG     AVG     WET     WET     WET     WET
1962 06720500         WET     WET     WET     WET     AVG     AVG     AVG     DRY     DRY     DRY     DRY     DRY
1962 06754000         WET     WET     WET     WET     AVG     AVG     WET     AVG     AVG     AVG     AVG     AVG
1963 06720500         DRY     DRY     DRY     DRY     DRY     DRY     DRY     DRY     AVG     DRY     DRY     DRY
1963 06754000         AVG     AVG     AVG     DRY     DRY     AVG     DRY     AVG     AVG     AVG     DRY     DRY
1964 06720500         DRY     AVG     DRY     DRY     AVG     DRY     DRY     DRY     DRY     DRY     AVG     AVG
1964 06754000         DRY     AVG     DRY     AVG     AVG     AVG     DRY     DRY     DRY     DRY     DRY     DRY
1965 06720500         AVG     AVG     AVG     AVG     AVG     WET     WET     WET     WET     WET     AVG     AVG
1965 06754000         DRY     AVG     AVG     DRY     AVG     WET     WET     WET     WET     WET     AVG     AVG
1966 06720500         AVG     AVG     AVG     AVG     DRY     DRY     DRY     AVG     AVG     AVG     AVG     AVG
1966 06754000         AVG     AVG     AVG     DRY     DRY     DRY     DRY     DRY     AVG     AVG     DRY     AVG
1967 06720500         AVG     AVG     AVG     AVG     DRY     DRY     AVG     AVG     AVG     AVG     AVG     AVG
1967 06754000         AVG     DRY     DRY     AVG     DRY     AVG     WET     AVG     AVG     AVG     AVG     AVG
1968 06720500         AVG     AVG     AVG     AVG     AVG     DRY     AVG     AVG     AVG     AVG     AVG     AVG
1968 06754000         AVG     AVG     AVG     AVG     DRY     AVG     DRY     AVG     AVG     AVG     DRY     DRY
1969 06720500         AVG     DRY     DRY     DRY     WET     WET     AVG     AVG     AVG     WET     WET     WET
1969 06754000         AVG     DRY     DRY     DRY     WET     WET     AVG     AVG     AVG     WET     WET     WET
1970 06720500         WET     AVG     AVG     WET     WET     WET     WET     WET     WET     WET     WET     WET
1970 06754000         WET     WET     AVG     WET     WET     WET     WET     AVG     WET     WET     WET     WET
1971 06720500         WET     WET     AVG     WET     AVG     AVG     AVG     AVG     WET     WET     WET     AVG
1971 06754000         WET     WET     AVG     WET     WET     AVG     AVG     AVG     WET     WET     WET     WET
1972 06720500         AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG
1972 06754000         WET     WET     AVG     AVG     DRY     AVG     AVG     AVG     WET     AVG     AVG     AVG
1973 06720500         AVG     AVG     WET     WET     WET     WET     WET     WET     WET     WET     WET     WET
1973 06754000         WET     WET     WET     WET     WET     WET     WET     AVG     WET     WET     WET     WET
1974 06720500         WET     WET     WET     WET     AVG     AVG     AVG     AVG     AVG     WET     AVG     AVG
1974 06754000         WET     WET     WET     WET     AVG     AVG     AVG     AVG     WET     AVG     WET     AVG
1975 06720500         AVG     AVG     AVG     AVG     AVG     AVG     WET     WET     AVG     AVG     AVG     AVG
1975 06754000         AVG     AVG     AVG     AVG     AVG     AVG     WET     WET     WET     AVG     AVG     AVG
1976 06720500         AVG     AVG     AVG     AVG     DRY     DRY     AVG     AVG     WET     WET     AVG     AVG
1976 06754000         AVG     AVG     AVG     AVG     AVG     DRY     AVG     WET     WET     AVG     AVG     AVG
1977 06720500         AVG     AVG     AVG     AVG     DRY     DRY     DRY     AVG     AVG     AVG     AVG     AVG
1977 06754000         AVG     AVG     AVG     AVG     DRY     DRY     AVG     AVG     AVG     AVG     AVG     AVG
1978 06720500         AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG
1978 06754000         AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG
1979 06720500         AVG     AVG     AVG     AVG     AVG     WET     WET     WET     AVG     WET     AVG     AVG
1979 06754000         AVG     AVG     AVG     AVG     WET     WET     AVG     WET     AVG     WET     WET     WET
1980 06720500         WET     WET     WET     WET     WET     WET     WET     AVG     AVG     AVG     AVG     AVG
1980 06754000         WET     WET     WET     WET     WET     WET     WET     AVG     WET     AVG     AVG     AVG
1981 06720500         AVG     AVG     AVG     AVG     AVG     DRY     DRY     AVG     AVG     AVG     AVG     AVG
1981 06754000         AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG
1982 06720500         AVG     AVG     AVG     AVG     AVG     DRY     AVG     WET     WET     WET     WET     WET
1982 06754000         AVG     AVG     AVG     DRY     AVG     AVG     WET     WET     WET     WET     WET     WET
1983 06720500         WET     WET     WET     WET     WET     WET     WET     WET     WET     AVG     WET     WET
1983 06754000         WET     WET     WET     WET     WET     WET     WET     WET     WET     WET     WET     WET
1984 06720500         WET     WET     WET     WET     WET     WET     WET     WET     WET     WET     WET     WET
1984 06754000         WET     WET     WET     WET     WET     WET     WET     WET     WET     WET     WET     WET
1985 06720500         WET     WET     WET     WET     WET     WET     WET     AVG     WET     WET     WET     WET
1985 06754000         WET     WET     WET     WET     WET     AVG     WET     AVG     WET     WET     WET     WET
1986 06720500         WET     AVG     AVG     WET     DRY     AVG     WET     AVG     AVG     WET     WET     WET
1986 06754000         WET     WET     WET     WET     AVG     WET     WET     WET     WET     WET     WET     WET
1987 06720500         WET     WET     WET     WET     WET     WET     AVG     WET     WET     AVG     WET     WET
1987 06754000         WET     WET     WET     WET     WET     AVG     AVG     AVG     AVG     AVG     WET     AVG
1988 06720500         WET     WET     WET     WET     AVG     AVG     AVG     AVG     AVG     AVG     AVG     WET
1988 06754000         WET     WET     WET     AVG     AVG     AVG     AVG     WET     AVG     AVG     AVG     AVG
1989 06720500         WET     WET     AVG     AVG     AVG     AVG     WET     AVG     AVG     AVG     AVG     AVG
1989 06754000         WET     WET     WET     AVG     AVG     AVG     AVG     AVG     WET     AVG     AVG     AVG
1990 06720500         WET     AVG     WET     AVG     AVG     DRY     AVG     AVG     WET     AVG     AVG     AVG
1990 06754000         AVG     AVG     WET     WET     AVG     AVG     AVG     AVG     WET     AVG     AVG     AVG
1991 06720500         WET     AVG     AVG     AVG     AVG     AVG     WET     WET     AVG     AVG     WET     WET
1991 06754000         WET     AVG     AVG     DRY     AVG     AVG     AVG     WET     AVG     AVG     WET     WET
1992 06720500         WET     WET     WET     AVG     DRY     AVG     AVG     AVG     AVG     AVG     AVG     WET
1992 06754000         WET     WET     WET     WET     AVG     AVG     AVG     WET     AVG     AVG     AVG     WET
1993 06720500         AVG     WET     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG
1993 06754000         AVG     WET     WET     AVG     AVG     AVG     AVG     AVG     WET     AVG     WET     WET
1994 06720500         AVG     AVG     AVG     AVG     AVG     AVG     DRY     AVG     AVG     AVG     AVG     AVG
1994 06754000         WET     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG
1995 06720500         AVG     AVG     AVG     AVG     WET     WET     WET     WET     WET     WET     WET     WET
1995 06754000         AVG     AVG     AVG     DRY     WET     WET     WET     WET     WET     WET     AVG     WET
1996 06720500         WET     AVG     AVG     AVG     AVG     AVG     AVG     AVG     WET     AVG     WET     WET
1996 06754000         WET     WET     AVG     AVG     AVG     AVG     WET     AVG     WET     WET     WET     AVG
1997 06720500         WET     WET     AVG     AVG     AVG     WET     WET     WET     WET     WET     WET     WET
1997 06754000         AVG     AVG     AVG     AVG     AVG     WET     WET     WET     WET     WET     WET     WET
1998 06720500         WET     WET     WET     WET     WET     AVG     WET     WET     WET     WET     WET     WET
1998 06754000         WET     WET     WET     WET     WET     AVG     WET     WET     AVG     WET     WET     WET
1999 06720500         WET     AVG     AVG     WET     WET     WET     WET     WET     WET     WET     WET     WET
1999 06754000         WET     AVG     AVG     WET     WET     WET     AVG     WET     WET     WET     WET     WET
2000 06720500         WET     WET     WET     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG
2000 06754000         WET     WET     WET     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG
2001 06720500         AVG     WET     WET     WET     AVG     AVG     AVG     AVG     AVG     WET     WET     AVG
2001 06754000         AVG     WET     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG
2002 06720500         AVG     WET     AVG     AVG     DRY     DRY     DRY     DRY     AVG     AVG     AVG     AVG
2002 06754000         AVG     AVG     AVG     DRY     DRY     DRY     DRY     DRY     DRY     DRY     AVG     DRY
2003 06720500         AVG     AVG     WET     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG
2003 06754000         AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     AVG     DRY     AVG     AVG
2004 06720500         AVG     WET     AVG     AVG     DRY     AVG     AVG     WET     AVG     WET     AVG     AVG
2004 06754000         DRY     AVG     AVG     AVG     AVG     AVG     AVG     WET     AVG     WET     AVG     AVG
2005 06720500         AVG     AVG     AVG     WET     AVG     AVG     AVG     AVG     AVG     WET     AVG     AVG
2005 06754000         AVG     AVG     AVG     AVG     AVG     WET     AVG     AVG     AVG     WET     AVG     AVG
2006 06720500         AVG     AVG     AVG     AVG     DRY     AVG     AVG     AVG     AVG     AVG     AVG     WET
2006 06754000         AVG     AVG     AVG     DRY     DRY     DRY     AVG     AVG     AVG     AVG     AVG     AVG
2007 06720500         WET     WET     WET     WET     WET     WET     AVG     AVG     AVG     WET     WET     AVG
2007 06754000         AVG     WET     WET     WET     WET     AVG     AVG     AVG     AVG     AVG     WET     AVG
2008 06720500         AVG     WET     WET     AVG     AVG     AVG     AVG     AVG     AVG  -999.0  -999.0  -999.0
2008 06754000         AVG     AVG     AVG     DRY     AVG     AVG     AVG     WET     WET  -999.0  -999.0  -999.0
