[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
MainTitleString = "Example of Weighted Traces"

[SubProduct 1]

GraphType = "Line"

[Data 1.1]

TSID = "08235350.USGS.Streamflow.Day[1995]~HydroBase"

[Data 1.2]

TSID = "08235350.USGS.Streamflow.Day[1996]~HydroBase"

[Data 1.3]

TSID = "08235350.USGS.Streamflow.Day[1997]~HydroBase"

[Data 1.4]

TSID = "08235350.USGS.Streamflow.Day[1998]~HydroBase"

[Data 1.5]

TSID = "08235350.USGS.Streamflow.Day[1999]~HydroBase"

[Data 1.6]

TSID = "08235350.USGS.Streamflow.Day.weighted~HydroBase"
TSAlias = "WeightedTS"
LineWidth = 3
Color = Black
